<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>in.n4smh.microservices.person</groupId>
		<artifactId>parent-pom</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<artifactId>swagger-central</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>PersonSwaggerCentral</name>
	<description>Swagger server for Person APIs</description>

	<properties>
		<person-parent-webflux.version>0.0.1-SNAPSHOT</person-parent-webflux.version>
		<person-shared.version>0.0.1-SNAPSHOT</person-shared.version>
	</properties>

	<dependencies>
		<!-- Start: Shared dependencies-->
		<dependency>
			<groupId>in.n4smh.microservices.person</groupId>
			<artifactId>parent-webflux</artifactId>
			<version>${person-parent-webflux.version}</version>
		</dependency>
		<dependency>
			<groupId>in.n4smh.microservices.person</groupId>
			<artifactId>shared</artifactId>
			<version>${person-shared.version}</version>
		</dependency>
		<!-- End -->
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<name>
							${nexus-docker-path}${project.artifactId}:${project.version}
						</name>
						<publish>true</publish>
					</image>
					<docker>
						<builderRegistry>
							<username>${nexus-ci-user}</username>
							<password>${nexus-ci-password}</password>
							<url>${nexus-docker-host}</url>
						</builderRegistry>
					</docker>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
