spring:
  application:
    name: ${person.swagger-central.name}

  security:
    user:
      name: ${person.swagger-central.security-user-name}
      password: ${person.swagger-central.security-user-password}

server:
  port: ${person.swagger-central.port}

management:
  tracing:
    sampling:
      probability: ${person.otlp-tracing-sampling-probability}
  otlp:
    metrics:
      export:
        url: ${person.otlp-metrics-uri}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${person.otlp-tracing-uri}
    logging:
      export:
        otlp:
          endpoint: ${person.otlp-logging-uri}
  endpoints:
    web:
      exposure:
        include:
        - info
        - health

logging:
  pattern:
    correlation: ${person.logging-pattern-correlation}

springdoc:
  show-actuator: true
  swagger-ui:
    enabled: ${person.swagger-enabled}
    urls:
    - name: ${person.gw.context}
      url: ${person.gw.uri}/v3/api-docs/${person.gw.context}

    - name: ${person.cud.context}
      url: ${person.cud.uri}/v3/api-docs/${person.cud.context}

    - name: ${person.query.context}
      url: ${person.query.uri}/v3/api-docs/${person.query.context}

  api-docs:
    enabled: ${person.swagger-enabled}
